# Generated by Django 5.2 on 2025-05-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.IntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.IntegerField()),
                ('tx_type', models.CharField(choices=[('deposit', '입금'), ('withdraw', '출금')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
