# Generated by Django 5.2 on 2025-05-06 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioRequest',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('member_no', models.IntegerField()),
                ('preset', models.CharField(blank=True, choices=[('aggressive', '공격형'), ('moderate', '중간형')], max_length=10, null=True)),
                ('balance_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '요청됨'), (1, '작업중'), (2, '완료됨'), (4, '자문 실패')], default=0)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritiesMarket',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioResult',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('request_no', models.IntegerField(editable=False, unique=True)),
                ('invested_balance', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['request_no'], name='portfolio_p_request_c3198b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioResultItem',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('result_no', models.IntegerField()),
                ('security_code', models.CharField(max_length=16)),
                ('security_name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField()),
                ('units', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['result_no'], name='portfolio_p_result__36eb10_idx')],
            },
        ),
    ]
