# Generated by Django 5.2 on 2025-05-06 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembersHistory',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('member_no', models.IntegerField()),
                ('event_code', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('request_meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['member_no', 'event_code'], name='user_member_member__6a1b0a_idx')],
            },
        ),
    ]
